import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    navDashboard: "Dashboard",
    navCalendar: "Calendar",
    navJournal: "Reflection Journal",
    navChat: "AI Companion",
    navSettings: "Profile",
    navLogout: "Log Out",
    sleepTarget: "Sleep Target",
    wakeTarget: "Wake Target",
    activeStreak: "Active Streak",
    streakDays: "Days",
    todaysTasks: "Today's Tasks",
    addTask: "Add Task",
    title: "Title",
    description: "Description",
    startTime: "Start Time",
    endTime: "End Time",
    priority: "Priority",
    category: "Category",
    save: "Save",
    cancel: "Cancel",
    high: "High",
    medium: "Medium",
    low: "Low",
    completed: "Completed",
    active: "Active",
    journalHeader: "Reflect on your Day",
    journalSub: "Writing down your thoughts before bed clears mental clutter and improves sleep quality.",
    journalPlaceholder: "What went well today? What did you focus on? Free write here...",
    saveEntry: "Save Reflection",
    downloadJSON: "Download JSON",
    downloadPDF: "Download PDF Summary",
    downloadAll: "Download All (PDF)",
    journalHistory: "Your Writing History",
    noEntries: "No reflection entries yet. Start writing tonight!",
    aiReflection: "Companion Reflection Analysis",
    calendarHeader: "Live Schedule Calendar",
    calendarSub: "Track task schedules and set customized alarms so you never miss a focus block.",
    eventsOn: "Events on",
    addEvent: "Add Calendar Alert",
    eventTitle: "Event Name",
    eventTime: "Alert Time",
    setAlert: "Set Alert",
    eventAlert: "Alert Set",
    noEvents: "No alerts set for this day.",
    delete: "Delete",
    settingsHeader: "My Profile",
    settingsSub: "Manage your name, email, sleep schedule, and target goals.",
    bedtimeProfile: "Bedtime & Focus Profile",
    nameLabel: "Your Name",
    goalLabel: "Productivity Target",
    notifications: "Notification Reminders",
    upcomingWarning: "Upcoming Focus Warning",
    preSleepReminder: "Night Pre-Sleep Planner Alarm",
    preBedPrompt: "Pre-Bed Journal Prompt",
    saveSettings: "Save Profile",
    settingsSaved: "Profile Saved",
    connectionState: "Connection State",
    serverUrl: "Server Endpoint URL",
    firebaseApiKey: "Firebase API Key",
    firebaseAuthDomain: "Firebase Auth Domain",
    firebaseProjectId: "Firebase Project ID",
    syncServer: "Sync Server Configuration",
    preferredLanguage: "Preferred Language"
  },
  te: {
    navDashboard: "డ్యాష్‌బోర్డ్",
    navCalendar: "క్యాలెండర్",
    navJournal: "రాత జర్నల్",
    navChat: "ఏఐ చాట్",
    navSettings: "ప్రొఫైల్",
    navLogout: "లాగ్ అవుట్",
    sleepTarget: "నిద్ర లక్ష్యం",
    wakeTarget: "మేల్కొనే లక్ష్యం",
    activeStreak: "సక్రియ స్ట్రీక్",
    streakDays: "రోజులు",
    todaysTasks: "నేటి పనులు",
    addTask: "పనిని జోడించు",
    title: "శీర్షిక",
    description: "వివరణ",
    startTime: "ప్రారంభ సమయం",
    endTime: "ముగింపు సమయం",
    priority: "ప్రాధాన్యత",
    category: "వర్గం",
    save: "సేవ్ చేయి",
    cancel: "రద్దు చేయి",
    high: "ఎక్కువ",
    medium: "మధ్యస్థం",
    low: "తక్కువ",
    completed: "పూర్తయింది",
    active: "క్రియాశీల",
    journalHeader: "ఈనాటి ఆలోచనలు",
    journalSub: "పడుకునే ముందు మీ ఆలోచనలను రాయడం వలన మనస్సు ప్రశాంతంగా ఉంటుంది మరియు నిద్ర నాణ్యత పెరుగుతుంది.",
    journalPlaceholder: "ఈ రోజు ఏమి బాగా జరిగింది? మీరు దేనిపై దృష్టి పెట్టారు? ఇక్కడ రాయండి...",
    saveEntry: "జర్నల్ సేవ్ చేయి",
    downloadJSON: "JSON డౌన్‌లోడ్",
    downloadPDF: "PDF సారాంశం",
    downloadAll: "అన్నీ డౌన్‌లోడ్ చేయి (PDF)",
    journalHistory: "మీ రచనల చరిత్ర",
    noEntries: "ఇంకా జర్నల్స్ రాయలేదు. ఈ రాత్రి నుండే రాయడం ప్రారంభించండి!",
    aiReflection: "ఏఐ ప్రతిబింబ విశ్లేషణ",
    calendarHeader: "షెడ్యూల్ క్యాలెండర్",
    calendarSub: "పనుల షెడ్యూల్‌లను ట్రాక్ చేయండి మరియు అలారాలను సెట్ చేసుకోండి.",
    eventsOn: "నాడు ఈవెంట్లు",
    addEvent: "క్యాలెండర్ అలర్ట్ జోడించు",
    eventTitle: "ఈవెంట్ పేరు",
    eventTime: "అలర్ట్ సమయం",
    setAlert: "అలర్ట్ సెట్ చేయి",
    eventAlert: "అలర్ట్ సెట్ చేయబడింది",
    noEvents: "ఈ రోజుకు అలర్ట్‌లు లేవు.",
    delete: "తొలగించు",
    settingsHeader: "నా ప్రొఫైల్",
    settingsSub: "మీ పేరు, ఇమెయిల్, నిద్ర సమయాలు మరియు లక్ష్యాలను కాన్ఫిగర్ చేయండి.",
    bedtimeProfile: "నిద్ర & దృష్టి ప్రొఫైల్",
    nameLabel: "మీ పేరు",
    goalLabel: "ఉత్పాదకత లక్ష్యం",
    notifications: "నోటిఫికేషన్ రిమైండర్లు",
    upcomingWarning: "రాబోయే పని అలర్ట్",
    preSleepReminder: "రాత్రి ప్లానర్ అలారం",
    preBedPrompt: "పడుకునే ముందు జర్నల్ గుర్తు చేయి",
    saveSettings: "ప్రొఫైల్ సేవ్ చేయి",
    settingsSaved: "ప్రొఫైల్ సేవ్ చేయబడింది",
    connectionState: "కనెక్షన్ స్థితి",
    serverUrl: "సర్వర్ URL",
    firebaseApiKey: "ఫైర్‌బేస్ API కీ",
    firebaseAuthDomain: "ఫైర్‌బేస్ ఆత్ డొమైన్",
    firebaseProjectId: "ఫైర్‌బేస్ ప్రాజెక్ట్ ID",
    syncServer: "సర్వర్ కాన్ఫిగరేషన్ సమకాలీకరించు",
    preferredLanguage: "భాష ఎంపిక"
  },
  hi: {
    navDashboard: "डैशबोर्ड",
    navCalendar: "कैलेंडर",
    navJournal: "रिफ्लेक्शन जर्नल",
    navChat: "एआई साथी",
    navSettings: "प्रोफ़ाइल",
    navLogout: "लॉग आउट",
    sleepTarget: "सोने का लक्ष्य",
    wakeTarget: "जागने का लक्ष्य",
    activeStreak: "सक्रिय स्ट्रीक",
    streakDays: "दिन",
    todaysTasks: "आज के कार्य",
    addTask: "कार्य जोड़ें",
    title: "शीर्षक",
    description: "विवरण",
    startTime: "आरंभ का समय",
    endTime: "समाप्त होने का समय",
    priority: "प्राथमिकता",
    category: "श्रेणी",
    save: "सहेजें",
    cancel: "रद्द करें",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    completed: "पूरा हो गया",
    active: "सक्रिय",
    journalHeader: "आज के विचारों पर विचार करें",
    journalSub: "सोने से पहले अपने विचारों को लिखने से मानसिक शांति मिलती है और नींद की गुणवत्ता में सुधार होता है।",
    journalPlaceholder: "आज क्या अच्छा रहा? आपका ध्यान किस पर था? यहाँ खुलकर लिखें...",
    saveEntry: "रिफ्लेक्शन सहेजें",
    downloadJSON: "JSON डाउनलोड करें",
    downloadPDF: "PDF सारांश",
    downloadAll: "सभी डाउनलोड करें (PDF)",
    journalHistory: "आपका लेखन इतिहास",
    noEntries: "अभी तक कोई रिफ्लेक्शन प्रविष्टि नहीं है। आज रात से लिखना शुरू करें!",
    aiReflection: "एआई रिफ्लेक्शन विश्लेषण",
    calendarHeader: "लाइव अनुसूची कैलेंडर",
    calendarSub: "कार्य अनुसूचियों को ट्रैक करें और अलार्म सेट करें ताकि आप कभी भी फोकस ब्लॉक न चूकें।",
    eventsOn: "कार्य दिनांक",
    addEvent: "कैलेंडर अलर्ट जोड़ें",
    eventTitle: "अलर्ट का नाम",
    eventTime: "अलर्ट का समय",
    setAlert: "अलर्ट सेट करें",
    eventAlert: "अलर्ट सेट हो गया",
    noEvents: "इस दिन के लिए कोई अलर्ट सेट नहीं है।",
    delete: "हटाएं",
    settingsHeader: "मेरी प्रोफ़ाइल",
    settingsSub: "अपना नाम, ईमेल, सोने का समय और लक्ष्यों को प्रबंधित करें।",
    bedtimeProfile: "नींद और फोकस प्रोफ़ाइल",
    nameLabel: "आपका नाम",
    goalLabel: "उत्पादकता लक्ष्य",
    notifications: "अधिसूचना अनुस्मारक",
    upcomingWarning: "आगामी कार्य चेतावनी",
    preSleepReminder: "रात सोने से पहले योजना अलार्म",
    preBedPrompt: "सोने से पहले जर्नल संकेत",
    saveSettings: "प्रोफ़ाइल सहेजें",
    settingsSaved: "प्रोफ़ाइल सहेजी गई",
    connectionState: "कनेक्शन की स्थिति",
    serverUrl: "सर्वर एंडपॉइंट URL",
    firebaseApiKey: "फायरबेस API कुंजी",
    firebaseAuthDomain: "फायरबेस ऑथ डोमेन",
    firebaseProjectId: "फायरबेस प्रोजेक्ट ID",
    syncServer: "सर्वर कॉन्फ़िगरेशन सिंक करें",
    preferredLanguage: "पसंदीदा भाषा"
  },
  es: {
    navDashboard: "Tablero",
    navCalendar: "Calendario",
    navJournal: "Diario de Reflexión",
    navChat: "Compañero IA",
    navSettings: "Perfil",
    navLogout: "Cerrar Sesión",
    sleepTarget: "Meta de Sueño",
    wakeTarget: "Meta de Despertar",
    activeStreak: "Racha Activa",
    streakDays: "Días",
    todaysTasks: "Tareas de Hoy",
    addTask: "Agregar Tarea",
    title: "Título",
    description: "Descripción",
    startTime: "Hora de inicio",
    endTime: "Hora de fin",
    priority: "Prioridad",
    category: "Categoría",
    save: "Guardar",
    cancel: "Cancelar",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    completed: "Completado",
    active: "Activo",
    journalHeader: "Reflexiona sobre tu día",
    journalSub: "Escribir tus pensamientos antes de acostarte despeja el desorden mental y mejora la calidad del sueño.",
    journalPlaceholder: "¿Qué salió bien hoy? ¿En qué te enfocaste? Escribe libremente aquí...",
    saveEntry: "Guardar Reflexión",
    downloadJSON: "Descargar JSON",
    downloadPDF: "Descargar Resumen PDF",
    downloadAll: "Descargar Todo (PDF)",
    journalHistory: "Historial de Escritura",
    noEntries: "No hay entradas de reflexión aún. ¡Empieza a escribir esta noche!",
    aiReflection: "Análisis de Reflexión de IA",
    calendarHeader: "Calendario de Horarios",
    calendarSub: "Realiza un seguimiento de tus tareas y configura alarmas personalizadas.",
    eventsOn: "Eventos el",
    addEvent: "Agregar Alerta de Calendario",
    eventTitle: "Nombre del Evento",
    eventTime: "Hora de Alerta",
    setAlert: "Configurar Alerta",
    eventAlert: "Alerta Establecida",
    noEvents: "No hay alertas configuradas para este día.",
    delete: "Eliminar",
    settingsHeader: "Mi Perfil",
    settingsSub: "Administre su nombre, correo electrónico, horario de sueño y objetivos.",
    bedtimeProfile: "Perfil de Sueño y Enfoque",
    nameLabel: "Tu Nombre",
    goalLabel: "Objetivo de Productividad",
    notifications: "Recordatorios de Notificación",
    upcomingWarning: "Advertencia de Tarea Próxima",
    preSleepReminder: "Alarma del Planificador Nocturno",
    preBedPrompt: "Recordatorio de Diario antes de Dormir",
    saveSettings: "Guardar Perfil",
    settingsSaved: "Perfil Guardado",
    connectionState: "Estado de la Conexión",
    serverUrl: "URL del Servidor",
    firebaseApiKey: "Clave API de Firebase",
    firebaseAuthDomain: "Dominio de Autenticación",
    firebaseProjectId: "ID del Proyecto de Firebase",
    syncServer: "Sincronizar Configuración del Servidor",
    preferredLanguage: "Idioma Preferido"
  },
  ta: {
    navDashboard: "டாஷ்போர்டு",
    navCalendar: "காலண்டர்",
    navJournal: "டைரி குறிப்புகள்",
    navChat: "ஏஐ அரட்டை",
    navSettings: "சுயவிவரம்",
    navLogout: "வெளியேறு",
    sleepTarget: "தூக்க நேரம்",
    wakeTarget: "விழிப்பு நேரம்",
    activeStreak: "செயலில் உள்ள நாட்கள்",
    streakDays: "நாட்கள்",
    todaysTasks: "இன்றைய பணிகள்",
    addTask: "பணியைச் சேர்",
    title: "தலைப்பு",
    description: "விளக்கம்",
    startTime: "ஆரம்ப நேரம்",
    endTime: "முடிவு நேரம்",
    priority: "முன்னுரிமை",
    category: "வகை",
    save: "சேமி",
    cancel: "ரத்து செய்",
    high: "அதிகம்",
    medium: "நடுத்தரம்",
    low: "குறைவு",
    completed: "முடிந்தது",
    active: "செயலில்",
    journalHeader: "இன்றைய நாளைப் பற்றி சிந்தியுங்கள்",
    journalSub: "தூங்குவதற்கு முன் உங்கள் எண்ணங்களை எழுதுவது மன அமைதியைத் தந்து தூக்கத்தின் தரத்தை உயர்த்தும்.",
    journalPlaceholder: "இன்று எது சிறப்பாக அமைந்தது? எதில் கவனம் செலுத்தினீர்கள்? இங்கே எழுதுங்கள்...",
    saveEntry: "குறிப்பைச் சேமி",
    downloadJSON: "JSON பதிவிறக்கம்",
    downloadPDF: "PDF சுருக்கம்",
    downloadAll: "அனைத்தும் பதிவிறக்கு (PDF)",
    journalHistory: "உங்கள் எழுத்து வரலாறு",
    noEntries: "இன்னும் குறிப்புகள் எதுவும் எழுதப்படவில்லை. இன்று இரவு தொடங்கவும்!",
    aiReflection: "ஏஐ குறிப்பு பகுப்பாய்வு",
    calendarHeader: "நேரலை காலண்டர்",
    calendarSub: "பணி அட்டவணைகளைக் கண்காணித்து அலாரங்களை அமைக்கவும்.",
    eventsOn: "நாளின் நிகழ்வுகள்",
    addEvent: "அலாரத்தை சேர்",
    eventTitle: "நிகழ்வின் பெயர்",
    eventTime: "அலார நேரம்",
    setAlert: "அலாரத்தை அமை",
    eventAlert: "அலாரம் அமைக்கப்பட்டது",
    noEvents: "இன்று எந்த அலாரமும் இல்லை.",
    delete: "அழி",
    settingsHeader: "என் சுயவிவரம்",
    settingsSub: "உங்கள் பெயர், மின்னஞ்சல், தூக்க நேரம் மற்றும் இலக்குகளை நிர்வகிக்கவும்.",
    bedtimeProfile: "தூக்கம் & கவனக் குறிப்பு",
    nameLabel: "உங்கள் பெயர்",
    goalLabel: "உற்பத்தித் திறன் இலக்கு",
    notifications: "அறிவிப்பு நினைவூட்டல்கள்",
    upcomingWarning: "வரவிருக்கும் பணி எச்சரிக்கை",
    preSleepReminder: "இரவு திட்டமிடல் அலாரம்",
    preBedPrompt: "தூங்கும் முன் எழுத நினைவூட்டு",
    saveSettings: "குறிப்பைச் சேமி",
    settingsSaved: "சேமிக்கப்பட்டது",
    connectionState: "இணைப்பு நிலை",
    serverUrl: "சர்வர் URL",
    firebaseApiKey: "Firebase API சாவி",
    firebaseAuthDomain: "Firebase Auth டொமைன்",
    firebaseProjectId: "Firebase திட்டத்தின் ID",
    syncServer: "சர்வர் அமைப்பைச் சேமி",
    preferredLanguage: "விருப்பமான மொழி"
  },
  kn: {
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navCalendar: "ಕ್ಯಾಲೆಂಡರ್",
    navJournal: "ದಿನಚರಿ ಜರ್ನಲ್",
    navChat: "ಎಐ ಚಾಟ್",
    navSettings: "ಪ್ರೊಫೈಲ್",
    navLogout: "ಲಾಗ್ ಔಟ್",
    sleepTarget: "ನಿದ್ರೆಯ ಗುರಿ",
    wakeTarget: "ಎಚ್ಚರಗೊಳ್ಳುವ ಗುರಿ",
    activeStreak: "ಸಕ್ರಿಯ ಸ್ಟ್ರೀಕ್",
    streakDays: "ದಿನಗಳು",
    todaysTasks: "ಇಂದಿನ ಕೆಲಸಗಳು",
    addTask: "ಕೆಲಸವನ್ನು ಸೇರಿಸಿ",
    title: "ಶೀರ್ಷಿಕೆ",
    description: "ವಿವರಣೆ",
    startTime: "ಪ್ರಾರಂಭದ ಸಮಯ",
    endTime: "ಮುಕ್ತಾಯದ ಸಮಯ",
    priority: "ಆದ್ಯತೆ",
    category: "ವರ್ಗ",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    high: "ಹೆಚ್ಚು",
    medium: "ಮಧ್ಯಮ",
    low: "ಕಡಿಮೆ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    active: "ಸಕ್ರಿಯ",
    journalHeader: "ಇಂದಿನ ದಿನದ ಬಗ್ಗೆ ಯೋಚಿಸಿ",
    journalSub: "ಮಲಗುವ ಮುನ್ನ ದಿನದ ವಿಚಾರಗಳನ್ನು ಬರೆಯುವುದರಿಂದ ಮಾನಸಿಕ ನೆಮ್ಮದಿ ಸಿಗುತ್ತದೆ ಹಾಗೂ ನಿದ್ರೆಯ ಗುಣಮಟ್ಟ ಹೆಚ್ಚುತ್ತದೆ.",
    journalPlaceholder: "ಇಂದು ಏನು ಚೆನ್ನಾಗಿ ನಡೆಯಿತು? ನೀವು ಯಾವುದರತ್ತ ಗಮನ ಹರಿಸಿದ್ದೀರಿ? ಇಲ್ಲಿ ಬರೆಯಿರಿ...",
    saveEntry: "ಉಳಿಸಿ",
    downloadJSON: "JSON ಡೌನ್‌ಲೋಡ್",
    downloadPDF: "PDF ಸಾರಾಂಶ",
    downloadAll: "ಎಲ್ಲವನ್ನೂ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (PDF)",
    journalHistory: "ಬರವಣಿಗೆಯ ಇತಿಹಾಸ",
    noEntries: "ಯಾವುದೇ ದಿನಚರಿ ಇನ್ನೂ ಬರೆದಿಲ್ಲ. ಇಂದೇ ಶುರುಮಾಡಿ!",
    aiReflection: "ಎಐ ದಿನಚರಿ ವಿಶ್ಲೇಷಣೆ",
    calendarHeader: "ವೇಳಾಪಟ್ಟಿ ಕ್ಯಾಲೆಂಡರ್",
    calendarSub: "ಕೆಲಸದ ವೇಳಾಪಟ್ಟಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಅಲಾರಂಗಳನ್ನ ಸೆಟ್ ಮಾಡಿ.",
    eventsOn: "ದಿನದ ಕಾರ್ಯಕ್ರಮಗಳು",
    addEvent: "ಅಲರ್ಟ್ ಸೇರಿಸಿ",
    eventTitle: "ಕಾರ್ಯಕ್ರಮದ ಹೆಸರು",
    eventTime: "ಅಲರ್ಟ್ ಸಮಯ",
    setAlert: "ಅಲರ್ಟ್ ಸೆಟ್ ಮಾಡಿ",
    eventAlert: "ಅಲರ್ಟ್ ಸೆಟ್ ಮಾಡಲಾಗಿದೆ",
    noEvents: "ಈ ದಿನ ಯಾವುದೇ ಅಲರ್ಟ್ ಇಲ್ಲ.",
    delete: "ಅಳಿಸಿ",
    settingsHeader: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    settingsSub: "ನಿಮ್ಮ ಹೆಸರು, ಇಮೇಲ್, ನಿದ್ರೆಯ ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ಗುರಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    bedtimeProfile: "ನಿದ್ರೆ ಮತ್ತು ಫೋಕಸ್ ಪ್ರೊಫೈಲ್",
    nameLabel: "ನಿಮ್ಮ ಹೆಸರು",
    goalLabel: "ಉತ್ಪಾದಕತೆಯ ಗುರಿ",
    notifications: "ನೋಟಿಫಿಕೇಶನ್ ಜ್ಞಾಪನೆಗಳು",
    upcomingWarning: "ಕೆಲಸದ ಜ್ಞಾಪನೆ",
    preSleepReminder: "ರಾತ್ರಿ ಪ್ಲಾನರ್ ಅಲಾರಂ",
    preBedPrompt: "ಮಲಗುವ ಮುನ್ನ ಬರೆಯಲು ಜ್ಞಾಪನೆ",
    saveSettings: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    settingsSaved: "ಉಳಿಸಲಾಗಿದೆ",
    connectionState: "ಕನೆಕ್ಷನ್ ಸ್ಥಿತಿ",
    serverUrl: "ಸರ್ವರ್ URL",
    firebaseApiKey: "ಫೈರ್‌ಬೇಸ್ API ಕೀ",
    firebaseAuthDomain: "ಫೈರ್‌ಬೇಸ್ ಆತ್ ಡೊಮೈನ್",
    firebaseProjectId: "ಫೈರ್‌ಬೇಸ್ ಪ್ರಾಜೆಕ್ಟ್ ID",
    syncServer: "ಸರ್ವರ್ ಸಿಂಕ್ ಮಾಡಿ",
    preferredLanguage: "ಆದ್ಯತೆಯ ಭಾಷೆ"
  },
  ml: {
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    navCalendar: "കലണ്ടർ",
    navJournal: "ദിനചര്യ ജേണൽ",
    navChat: "എഐ കൂട്ടുകാരൻ",
    navSettings: "പ്രൊഫൈൽ",
    navLogout: "ലോഗ് ഔട്ട്",
    sleepTarget: "ഉറക്ക സമയം",
    wakeTarget: "ഉണരുന്ന സമയം",
    activeStreak: "സജീവ സ്ട്രീക്ക്",
    streakDays: "ദിവസങ്ങൾ",
    todaysTasks: "ഇന്നത്തെ ജോലികൾ",
    addTask: "ജോലി ചേർക്കുക",
    title: "തലക്കെട്ട്",
    description: "വിവരണം",
    startTime: "തുടങ്ങുന്ന സമയം",
    endTime: "അവസാനിക്കുന്ന സമയം",
    priority: "മുൻഗണന",
    category: "വിഭാഗം",
    save: "സൂക്ഷിക്കുക",
    cancel: "റദ്ദാക്കുക",
    high: "കൂടിയത്",
    medium: "മിതമായത്",
    low: "കുറഞ്ഞത്",
    completed: "പൂർത്തിയായി",
    active: "സജീവം",
    journalHeader: "ഇന്നത്തെ ദിവസത്തെ വിലയിരുത്തുക",
    journalSub: "ഉറങ്ങാൻ പോകുന്നതിന് മുൻപ് ചിന്തകൾ എഴുതിവെയ്ക്കുന്നത് മനസ്സിന് ശാന്തി നൽകുകയും ഉറക്കം മെച്ചപ്പെടുത്തുകയും ചെയ്യും.",
    journalPlaceholder: "ഇന്ന് എന്തൊക്കെ നന്നായി നടന്നു? നിങ്ങളുടെ ശ്രദ്ധ എന്തിലായിരുന്നു? ഇവിടെ എഴുതുക...",
    saveEntry: "സൂക്ഷിക്കുക",
    downloadJSON: "JSON ഡൗൺലോഡ്",
    downloadPDF: "PDF സംഗ്രഹം",
    downloadAll: "എല്ലാം ഡൗൺലോഡ് ചെയ്യുക (PDF)",
    journalHistory: "നിങ്ങളുടെ എഴുത്തു ചരിത്രം",
    noEntries: "ഇതുവരെ ജേണലുകൾ എഴുതിയിട്ടില്ല. ഇന്ന് രാത്രി തന്നെ തുടങ്ങൂ!",
    aiReflection: "എഐ വിശകലനം",
    calendarHeader: "ഷെഡ്യൂൾ കലണ്ടർ",
    calendarSub: "നിങ്ങളുടെ ജോലികൾ ട്രാക്ക് ചെയ്യുകയും അലാറങ്ങൾ ക്രമീകരിക്കുകയും ചെയ്യുക.",
    eventsOn: "ദിവസത്തെ ഇവന്റുകൾ",
    addEvent: "അലേർട്ട് ചേർക്കുക",
    eventTitle: "ഇവന്റിന്റെ പേര്",
    eventTime: "അലേർട്ട് സമയം",
    setAlert: "അലേർട്ട് ക്രമീകരിക്കുക",
    eventAlert: "അലേർട്ട് ക്രമീകരിച്ചു",
    noEvents: "ഇന്ന് അലേർട്ടുകൾ ഒന്നുമില്ല.",
    delete: "നീക്കം ചെയ്യുക",
    settingsHeader: "എന്റെ പ്രൊഫൈൽ",
    settingsSub: "നിങ്ങളുടെ പേര്, ഇമെയിൽ, ഉറക്ക സമയം, ലക്ഷ്യങ്ങൾ എന്നിവ ക്രമീകരിക്കുക.",
    bedtimeProfile: "ഉറക്കവും ശ്രദ്ധയും",
    nameLabel: "നിങ്ങളുടെ പേര്",
    goalLabel: "ഉൽപ്പാദനക്ഷമത ലക്ഷ്യം",
    notifications: "നോട്ടിഫിക്കേഷൻ ഓർമ്മപ്പെടുത്തലുകൾ",
    upcomingWarning: "വരാനിരിക്കുന്ന ജോലി മുന്നറിയിപ്പ്",
    preSleepReminder: "രാത്രി പ്ലാനർ അലാറം",
    preBedPrompt: "ഉറങ്ങുന്നതിന് മുൻപ് എഴുതാൻ ഓർമ്മപ്പെടുത്തുക",
    saveSettings: "പ്രൊഫൈൽ സൂക്ഷിക്കുക",
    settingsSaved: "പ്രൊഫൈൽ സൂക്ഷിച്ചു",
    connectionState: "കണക്ഷൻ നില",
    serverUrl: "സെർവർ URL",
    firebaseApiKey: "ഫയർബേസ് API കീ",
    firebaseAuthDomain: "ഫയർബേസ് ഓത്ത് ഡൊമൈൻ",
    firebaseProjectId: "ഫയർബേസ് പ്രൊജക്റ്റ് ID",
    syncServer: "സെർവർ കോൺഫിഗറേഷൻ സിങ്ക് ചെയ്യുക",
    preferredLanguage: "തിരഞ്ഞെടുത്ത ഭാഷ"
  },
  mr: {
    navDashboard: "डॅशबोर्ड",
    navCalendar: "कॅलेंडर",
    navJournal: "दैनंदिन जर्नल",
    navChat: "एआय मित्र",
    navSettings: "प्रोफाइल",
    navLogout: "लॉग आउट",
    sleepTarget: "झोपण्याचे उद्दिष्ट",
    wakeTarget: "उठण्याचे उद्दिष्ट",
    activeStreak: "सक्रिय स्ट्रीक",
    streakDays: "दिवस",
    todaysTasks: "आजची कामे",
    addTask: "काम जोडा",
    title: "शीर्षक",
    description: "वर्णन",
    startTime: "सुरुवात वेळ",
    endTime: "समाप्ती वेळ",
    priority: "प्राधान्य",
    category: "वर्ग",
    save: "जतन करा",
    cancel: "रद्द करा",
    high: "उच्च",
    medium: "मध्यम",
    low: "कमी",
    completed: "पूर्ण झाले",
    active: "सक्रिय",
    journalHeader: "आजच्या दिवसाचे पुनरावलोकन करा",
    journalSub: "झोपण्यापूर्वी विचार लिहून ठेवल्याने मानसिक शांतता मिळते आणि झोपेची गुणवत्ता सुधारते.",
    journalPlaceholder: "आज काय चांगले घडले? तुमचे लक्ष कशावर होते? इथे लिहा...",
    saveEntry: "जतन करा",
    downloadJSON: "JSON डाउनलोड",
    downloadPDF: "PDF सारांश",
    downloadAll: "सर्व डाउनलोड करा (PDF)",
    journalHistory: "तुमचा लेखन इतिहास",
    noEntries: "अजून एकही नोंद नाही. आज रात्रीपासून लिहायला सुरुवात करा!",
    aiReflection: "एआय विश्लेषण",
    calendarHeader: "वेळापत्रक कॅलेंडर",
    calendarSub: "कामाच्या वेळापत्रकाचा मागोवा घ्या आणि अलार्म सेट करा.",
    eventsOn: "दिवसाचे कार्यक्रम",
    addEvent: "अलर्ट जोडा",
    eventTitle: "कार्यक्रमाचे नाव",
    eventTime: "अलर्ट वेळ",
    setAlert: "अलर्ट सेट करा",
    eventAlert: "अलर्ट सेट केला",
    noEvents: "आज कोणताही अलर्ट सेट नाही.",
    delete: "हटवा",
    settingsHeader: "माझी प्रोफाइल",
    settingsSub: "तुमचे नाव, ईमेल, झोपेचे वेळापत्रक आणि उद्दिष्टे व्यवस्थापित करा.",
    bedtimeProfile: "झोप आणि लक्ष केंद्रित प्रोफाइल",
    nameLabel: "तुमचे नाव",
    goalLabel: "उत्पादकता उद्दिष्ट",
    notifications: "सूचना स्मरणपत्रे",
    upcomingWarning: "कामाचा इशारा",
    preSleepReminder: "रात्रीचे नियोजन अलार्म",
    preBedPrompt: "झोपण्यापूर्वी लिहिण्याची आठवण",
    saveSettings: "प्रोफाइल जतन करा",
    settingsSaved: "जतन केले",
    connectionState: "कनेक्शन स्थिती",
    serverUrl: "सर्व्हर URL",
    firebaseApiKey: "फायरबेस API की",
    firebaseAuthDomain: "फायरबेस ऑथ डोमेन",
    firebaseProjectId: "फायरबेस प्रोजेक्ट ID",
    syncServer: "सर्व्हर सिंक करा",
    preferredLanguage: "पसंतीची भाषा"
  },
  fr: {
    navDashboard: "Tableau de bord",
    navCalendar: "Calendrier",
    navJournal: "Journal de Réflexion",
    navChat: "Compagnon IA",
    navSettings: "Profil",
    navLogout: "Déconnexion",
    sleepTarget: "Objectif Sommeil",
    wakeTarget: "Objectif Réveil",
    activeStreak: "Série Active",
    streakDays: "Jours",
    todaysTasks: "Tâches d'aujourd'hui",
    addTask: "Ajouter Tâche",
    title: "Titre",
    description: "Description",
    startTime: "Heure de début",
    endTime: "Heure de fin",
    priority: "Priorité",
    category: "Catégorie",
    save: "Enregistrer",
    cancel: "Annuler",
    high: "Haute",
    medium: "Moyenne",
    low: "Basse",
    completed: "Terminée",
    active: "Active",
    journalHeader: "Réfléchissez à votre journée",
    journalSub: "Écrire vos pensées avant de dormir libère l'esprit et améliore la qualité du sommeil.",
    journalPlaceholder: "Qu'est-ce qui s'est bien passé aujourd'hui ? Sur quoi vous êtes-vous concentré ? Écrivez librement...",
    saveEntry: "Enregistrer la Réflexion",
    downloadJSON: "Télécharger JSON",
    downloadPDF: "Télécharger Résumé PDF",
    downloadAll: "Télécharger Tout (PDF)",
    journalHistory: "Historique d'Écriture",
    noEntries: "Aucune entrée pour l'instant. Commencez à écrire ce soir !",
    aiReflection: "Analyse de Réflexion IA",
    calendarHeader: "Calendrier des Tâches",
    calendarSub: "Suivez vos horaires et configurez des alertes personnalisées.",
    eventsOn: "Événements le",
    addEvent: "Ajouter une Alerte",
    eventTitle: "Nom de l'Événement",
    eventTime: "Heure de l'Alerte",
    setAlert: "Définir l'Alerte",
    eventAlert: "Alerte Définie",
    noEvents: "Aucune alerte définie pour ce jour.",
    delete: "Supprimer",
    settingsHeader: "Paramètres Système",
    settingsSub: "Gérez vos objectifs de sommeil, vos alarmes et les options de synchronisation.",
    bedtimeProfile: "Profil de Sommeil & Concentration",
    nameLabel: "Votre Nom",
    goalLabel: "Objectif de Productivité",
    notifications: "Rappels de Notification",
    upcomingWarning: "Alerte de Tâche Imminente",
    preSleepReminder: "Alarme de Planification du Soir",
    preBedPrompt: "Rappel de Journal avant le Coucher",
    saveSettings: "Enregistrer le Profil",
    settingsSaved: "Profil Enregistré",
    connectionState: "État de la Connexión",
    serverUrl: "URL du Serveur",
    firebaseApiKey: "Clé API Firebase",
    firebaseAuthDomain: "Domaine d'Authentification",
    firebaseProjectId: "ID de Projet Firebase",
    syncServer: "Synchroniser Configuration Serveur",
    preferredLanguage: "Langue Préférée"
  },
  de: {
    navDashboard: "Dashboard",
    navCalendar: "Kalender",
    navJournal: "Tagebuch",
    navChat: "KI-Begleiter",
    navSettings: "Profil",
    navLogout: "Abmelden",
    sleepTarget: "Schlafziel",
    wakeTarget: "Weckziel",
    activeStreak: "Aktive Serie",
    streakDays: "Tage",
    todaysTasks: "Heutige Aufgaben",
    addTask: "Aufgabe hinzufügen",
    title: "Titel",
    description: "Beschreibung",
    startTime: "Startzeit",
    endTime: "Endzeit",
    priority: "Priorität",
    category: "Kategorie",
    save: "Speichern",
    cancel: "Abbrechen",
    high: "Hoch",
    medium: "Mittel",
    low: "Niedrig",
    completed: "Abgeschlossen",
    active: "Aktiv",
    journalHeader: "Reflektieren Sie Ihren Tag",
    journalSub: "Das Aufschreiben Ihrer Gedanken vor dem Schlafengehen baut Stress ab und verbessert die Schlafqualität.",
    journalPlaceholder: "Was lief heute gut? Worauf haben Sie sich konzentriert? Schreiben Sie frei...",
    saveEntry: "Eintrag speichern",
    downloadJSON: "JSON herunterladen",
    downloadPDF: "PDF-Zusammenfassung herunterladen",
    downloadAll: "Alles herunterladen (PDF)",
    journalHistory: "Verlauf Ihrer Einträge",
    noEntries: "Noch keine Einträge. Fangen Sie heute Nacht an zu schreiben!",
    aiReflection: "KI-Reflexionsanalyse",
    calendarHeader: "Zeitplan-Kalender",
    calendarSub: "Verfolgen Sie Ihre Aufgabenzeiten und richten Sie benutzerdefinierte Alarme ein.",
    eventsOn: "Ereignisse am",
    addEvent: "Kalenderalarm hinzufügen",
    eventTitle: "Ereignisname",
    eventTime: "Alarmzeit",
    setAlert: "Alarm einstellen",
    eventAlert: "Alarm eingestellt",
    noEvents: "Keine Alarme für diesen Tag eingestellt.",
    delete: "Löschen",
    settingsHeader: "Mein Profil",
    settingsSub: "Verwalten Sie Ihren Namen, Ihre E-Mail-Adresse, Ihren Schlafplan und Ihre Ziele.",
    bedtimeProfile: "Schlaf- und Fokusprofil",
    nameLabel: "Ihr Name",
    goalLabel: "Produktivitätsziel",
    notifications: "Benachrichtigungserinnerungen",
    upcomingWarning: "Anstehende Aufgabenwarnung",
    preSleepReminder: "Planungswecker vor dem Schlafen",
    preBedPrompt: "Erinnerung an Tagebuch vor dem Bett",
    saveSettings: "Profil speichern",
    settingsSaved: "Profil gespeichert",
    connectionState: "Verbindungsstatus",
    serverUrl: "Server-Endpunkt-URL",
    firebaseApiKey: "Firebase-API-Schlüssel",
    firebaseAuthDomain: "Firebase-Auth-Domain",
    firebaseProjectId: "Firebase-Projekt-ID",
    syncServer: "Serverkonfiguration synchronisieren",
    preferredLanguage: "Bevorzugte Sprache"
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('sleep_clarity_language') || 'en');

  const changeLanguage = (lang) => {
    localStorage.setItem('sleep_clarity_language', lang);
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
